version: '2'
services:
    queen-app:
        image: queen
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://queen-mysql:3306/queen?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=queen-elasticsearch:9300
        ports:
            - 8080:8080
    queen-mysql:
        extends:
            file: mysql.yml
            service: queen-mysql
    queen-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: queen-elasticsearch
